import Layout from "../components/layout";
import Head from "next/head";
import ProjectItem from "../components/projects/project-item";
import { TOKEN, DATABASE_ID } from "../config/index";

export default function Projects({ projects }) {
  return (
    <Layout>
      <Head>
        <title>김재준의 포트폴리오 | 영상 포트폴리오 | </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="flex flex-col items-center justify-center min-h-screen mb-10">
            <h1 className="text-4xl font-bold sm:text-6xl">
              총 포트폴리오 :
              <span className="pl-4 text-blue-500">
                {projects.results.length}
              </span>
            </h1>

            <div className="grid gird-cols-1 xl:grid-cols-3 py-10 m-6 gap-2 w-full">
              {projects.results.map((aProject) => (
                <ProjectItem key={aProject.id} data={aProject} />
              ))}
            </div>
          </div>
        </div>
      </section>
    </Layout>
  );
}

export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Notion-Version": "2022-02-22",
      "Content-Type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      page_size: 200,
      sorts: [
        {
          property: "제작년도",
          direction: "ascending",
        },
        {
          property: "제목",
          direction: "ascending",
        },
      ],
    }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );

  const projects = await res.json();

  return {
    props: { projects },
  };
}
